-- Rollback des Landtag-Vollmodell-PREPARED-Seeds (Berlin/Brandenburg).
-- Loescht NUR die hier eingefuegten Ids. Entitaeten werden GUARDED geloescht:
-- nur wenn kein Herausgeber sie referenziert (publishers.entity_id, on delete set null waere
-- zwar harmlos, aber der Guard haelt die Referenz-Wahrheit konsistent).
begin;
delete from public.electoral_districts where id in ('wk-agh-mitte-1', 'wk-agh-mitte-2', 'wk-agh-mitte-3', 'wk-agh-mitte-4', 'wk-agh-mitte-5', 'wk-agh-mitte-6', 'wk-agh-mitte-7', 'wk-agh-friedrichshain-kreuzberg-1', 'wk-agh-friedrichshain-kreuzberg-2', 'wk-agh-friedrichshain-kreuzberg-3', 'wk-agh-friedrichshain-kreuzberg-4', 'wk-agh-friedrichshain-kreuzberg-5', 'wk-agh-pankow-1', 'wk-agh-pankow-2', 'wk-agh-pankow-3', 'wk-agh-pankow-4', 'wk-agh-pankow-5', 'wk-agh-pankow-6', 'wk-agh-pankow-7', 'wk-agh-pankow-8', 'wk-agh-pankow-9', 'wk-agh-charlottenburg-wilmersdorf-1', 'wk-agh-charlottenburg-wilmersdorf-2', 'wk-agh-charlottenburg-wilmersdorf-3', 'wk-agh-charlottenburg-wilmersdorf-4', 'wk-agh-charlottenburg-wilmersdorf-5', 'wk-agh-charlottenburg-wilmersdorf-6', 'wk-agh-charlottenburg-wilmersdorf-7', 'wk-agh-spandau-1', 'wk-agh-spandau-2', 'wk-agh-spandau-3', 'wk-agh-spandau-4', 'wk-agh-spandau-5', 'wk-agh-steglitz-zehlendorf-1', 'wk-agh-steglitz-zehlendorf-2', 'wk-agh-steglitz-zehlendorf-3', 'wk-agh-steglitz-zehlendorf-4', 'wk-agh-steglitz-zehlendorf-5', 'wk-agh-steglitz-zehlendorf-6', 'wk-agh-steglitz-zehlendorf-7', 'wk-agh-tempelhof-schoeneberg-1', 'wk-agh-tempelhof-schoeneberg-2', 'wk-agh-tempelhof-schoeneberg-3', 'wk-agh-tempelhof-schoeneberg-4', 'wk-agh-tempelhof-schoeneberg-5', 'wk-agh-tempelhof-schoeneberg-6', 'wk-agh-tempelhof-schoeneberg-7', 'wk-agh-neukoelln-1', 'wk-agh-neukoelln-2', 'wk-agh-neukoelln-3', 'wk-agh-neukoelln-4', 'wk-agh-neukoelln-5', 'wk-agh-neukoelln-6', 'wk-agh-treptow-koepenick-1', 'wk-agh-treptow-koepenick-2', 'wk-agh-treptow-koepenick-3', 'wk-agh-treptow-koepenick-4', 'wk-agh-treptow-koepenick-5', 'wk-agh-treptow-koepenick-6', 'wk-agh-treptow-koepenick-7', 'wk-agh-marzahn-hellersdorf-1', 'wk-agh-marzahn-hellersdorf-2', 'wk-agh-marzahn-hellersdorf-3', 'wk-agh-marzahn-hellersdorf-4', 'wk-agh-marzahn-hellersdorf-5', 'wk-agh-marzahn-hellersdorf-6', 'wk-agh-lichtenberg-1', 'wk-agh-lichtenberg-2', 'wk-agh-lichtenberg-3', 'wk-agh-lichtenberg-4', 'wk-agh-lichtenberg-5', 'wk-agh-lichtenberg-6', 'wk-agh-reinickendorf-1', 'wk-agh-reinickendorf-2', 'wk-agh-reinickendorf-3', 'wk-agh-reinickendorf-4', 'wk-agh-reinickendorf-5', 'wk-agh-reinickendorf-6', 'wk-ltbb-1', 'wk-ltbb-2', 'wk-ltbb-3', 'wk-ltbb-4', 'wk-ltbb-5', 'wk-ltbb-6', 'wk-ltbb-7', 'wk-ltbb-8', 'wk-ltbb-9', 'wk-ltbb-10', 'wk-ltbb-11', 'wk-ltbb-12', 'wk-ltbb-13', 'wk-ltbb-14', 'wk-ltbb-15', 'wk-ltbb-16', 'wk-ltbb-17', 'wk-ltbb-18', 'wk-ltbb-19', 'wk-ltbb-20', 'wk-ltbb-21', 'wk-ltbb-22', 'wk-ltbb-23', 'wk-ltbb-24', 'wk-ltbb-25', 'wk-ltbb-26', 'wk-ltbb-27', 'wk-ltbb-28', 'wk-ltbb-29', 'wk-ltbb-30', 'wk-ltbb-31', 'wk-ltbb-32', 'wk-ltbb-33', 'wk-ltbb-34', 'wk-ltbb-35', 'wk-ltbb-36', 'wk-ltbb-37', 'wk-ltbb-38', 'wk-ltbb-39', 'wk-ltbb-40', 'wk-ltbb-41', 'wk-ltbb-42', 'wk-ltbb-43', 'wk-ltbb-44');
delete from public.political_entities e where e.id in ('committee-agh-haupt', 'committee-agh-petition', 'committee-agh-recht', 'committee-agh-inneres', 'committee-agh-verfassungsschutz', 'committee-agh-arbeit-soziales', 'committee-agh-bildung', 'committee-agh-bund-europa', 'committee-agh-digital', 'committee-agh-gesundheit', 'committee-agh-integration', 'committee-agh-kultur', 'committee-agh-mobilitaet', 'committee-agh-sport', 'committee-agh-stadtentwicklung', 'committee-agh-umwelt', 'committee-agh-wirtschaft', 'committee-agh-wissenschaft', 'group-agh-cdu', 'group-agh-spd', 'group-agh-gruene', 'group-agh-afd', 'ministry-be-senatskanzlei', 'ministry-be-asgiva', 'ministry-be-bjf', 'ministry-be-fin', 'ministry-be-inn', 'ministry-be-just', 'ministry-be-kult', 'ministry-be-mvku', 'ministry-be-stadt', 'ministry-be-web', 'ministry-be-wgp', 'authority-be-rechnungshof', 'authority-be-datenschutz', 'authority-be-landeswahlleitung', 'committee-ltbb-haupt', 'committee-ltbb-petition', 'committee-ltbb-wahlpruefung', 'committee-ltbb-inneres', 'committee-ltbb-recht', 'committee-ltbb-bildung', 'committee-ltbb-wissenschaft', 'committee-ltbb-soziales', 'committee-ltbb-wirtschaft', 'committee-ltbb-landwirtschaft', 'committee-ltbb-infrastruktur', 'committee-ltbb-haushalt', 'committee-ltbb-haushaltskontrolle', 'committee-ltbb-europa', 'group-ltbb-spd', 'group-ltbb-afd', 'group-ltbb-cdu', 'group-ltbb-bsw', 'group-ltbb-wfb', 'ministry-bb-stk', 'ministry-bb-mik', 'ministry-bb-mdf', 'ministry-bb-mdjd', 'ministry-bb-mweke', 'ministry-bb-masgz', 'ministry-bb-mbjs', 'ministry-bb-mwfk', 'ministry-bb-mleuv', 'ministry-bb-mil', 'authority-bb-lrh', 'authority-bb-verfg', 'authority-bb-lda', 'authority-bb-landeswahlleitung')
  and not exists (select 1 from public.publishers pu where pu.entity_id = e.id);
commit;
notify pgrst, 'reload schema';
