-- Helmut — Landtag-Vollmodell Berlin/Brandenburg · PREPARED-Seed (generiert, idempotent, NICHT-destruktiv).
-- Generiert von scripts/generate-landtag-vollmodell-seed.js. NICHT von Hand editieren.
-- NUR Entitaeten + Wahlkreise: KEINE Abrufwege, KEINE Pakete, KEINE Statusaenderungen -> aktiviert NICHTS.
-- FREIGABEPFLICHTIG: Anwenden auf Production nur nach Gruender-Freigabe (docs/landtag/ Aktivierungscheckliste).
-- VOR DEM ANWENDEN AMTLICH PRUEFEN (verifiziert=false):
--   - authority-bb-landeswahlleitung: Landeswahlleiterin des Landes Brandenburg
--   - wk-ltbb-28: Dahme-Spreewald III
--   - wk-ltbb-34: Märkisch-Oderland IV
--   - wk-ltbb-42: Spree-Neiße II
begin;

-- 1) Politische Entitaeten (69: Ausschuesse/Fraktionen/Gruppen/Verwaltungen/Ministerien/Behoerden BE+BB)
insert into public.political_entities (id, entity_type, name, canonical_key, level, geography_id, aliases) values
  ('committee-agh-haupt', 'committee', 'Hauptausschuss (Abgeordnetenhaus von Berlin)', null, 'land', 'geo-land-berlin', array['Hauptausschuss Berlin']),
  ('committee-agh-petition', 'committee', 'Petitionsausschuss (Abgeordnetenhaus von Berlin)', null, 'land', 'geo-land-berlin', array['Petitionsausschuss Berlin']),
  ('committee-agh-recht', 'committee', 'Ausschuss für Verfassungs- und Rechtsangelegenheiten, Geschäftsordnung, Verbraucherschutz', null, 'land', 'geo-land-berlin', '{}'),
  ('committee-agh-inneres', 'committee', 'Ausschuss für Inneres, Sicherheit und Ordnung', null, 'land', 'geo-land-berlin', '{}'),
  ('committee-agh-verfassungsschutz', 'committee', 'Ausschuss für Verfassungsschutz', null, 'land', 'geo-land-berlin', '{}'),
  ('committee-agh-arbeit-soziales', 'committee', 'Ausschuss für Arbeit und Soziales', null, 'land', 'geo-land-berlin', array['Ausschuss für Arbeit und Soziales (Berlin)']),
  ('committee-agh-bildung', 'committee', 'Ausschuss für Bildung, Jugend und Familie', null, 'land', 'geo-land-berlin', '{}'),
  ('committee-agh-bund-europa', 'committee', 'Ausschuss für Bundes- und Europaangelegenheiten, Medien', null, 'land', 'geo-land-berlin', '{}'),
  ('committee-agh-digital', 'committee', 'Ausschuss für Digitalisierung und Datenschutz', null, 'land', 'geo-land-berlin', '{}'),
  ('committee-agh-gesundheit', 'committee', 'Ausschuss für Gesundheit und Pflege', null, 'land', 'geo-land-berlin', '{}'),
  ('committee-agh-integration', 'committee', 'Ausschuss für Integration, Frauen und Gleichstellung, Vielfalt und Antidiskriminierung', null, 'land', 'geo-land-berlin', '{}'),
  ('committee-agh-kultur', 'committee', 'Ausschuss für Kultur, Engagement und Demokratieförderung', null, 'land', 'geo-land-berlin', '{}'),
  ('committee-agh-mobilitaet', 'committee', 'Ausschuss für Mobilität und Verkehr', null, 'land', 'geo-land-berlin', '{}'),
  ('committee-agh-sport', 'committee', 'Ausschuss für Sport', null, 'land', 'geo-land-berlin', array['Sportausschuss Berlin']),
  ('committee-agh-stadtentwicklung', 'committee', 'Ausschuss für Stadtentwicklung, Bauen und Wohnen', null, 'land', 'geo-land-berlin', '{}'),
  ('committee-agh-umwelt', 'committee', 'Ausschuss für Umwelt- und Klimaschutz', null, 'land', 'geo-land-berlin', '{}'),
  ('committee-agh-wirtschaft', 'committee', 'Ausschuss für Wirtschaft, Energie und Betriebe', null, 'land', 'geo-land-berlin', '{}'),
  ('committee-agh-wissenschaft', 'committee', 'Ausschuss für Wissenschaft und Forschung', null, 'land', 'geo-land-berlin', '{}'),
  ('group-agh-cdu', 'parliamentary_group', 'CDU-Fraktion im Abgeordnetenhaus von Berlin', null, 'land', 'geo-land-berlin', array['CDU-Fraktion Berlin']),
  ('group-agh-spd', 'parliamentary_group', 'SPD-Fraktion im Abgeordnetenhaus von Berlin', null, 'land', 'geo-land-berlin', array['SPD-Fraktion Berlin']),
  ('group-agh-gruene', 'parliamentary_group', 'Fraktion Bündnis 90/Die Grünen im Abgeordnetenhaus von Berlin', null, 'land', 'geo-land-berlin', array['Grüne Fraktion Berlin']),
  ('group-agh-afd', 'parliamentary_group', 'AfD-Fraktion im Abgeordnetenhaus von Berlin', null, 'land', 'geo-land-berlin', array['AfD-Fraktion Berlin']),
  ('ministry-be-senatskanzlei', 'ministry', 'Senatskanzlei Berlin', null, 'land', 'geo-land-berlin', array['Der Regierende Bürgermeister von Berlin – Senatskanzlei', 'Senatskanzlei']),
  ('ministry-be-asgiva', 'ministry', 'Senatsverwaltung für Arbeit, Soziales, Gleichstellung, Integration, Vielfalt und Antidiskriminierung', null, 'land', 'geo-land-berlin', array['SenASGIVA']),
  ('ministry-be-bjf', 'ministry', 'Senatsverwaltung für Bildung, Jugend und Familie', null, 'land', 'geo-land-berlin', array['SenBJF']),
  ('ministry-be-fin', 'ministry', 'Senatsverwaltung für Finanzen', null, 'land', 'geo-land-berlin', array['SenFin']),
  ('ministry-be-inn', 'ministry', 'Senatsverwaltung für Inneres und Sport', null, 'land', 'geo-land-berlin', array['SenInnSport']),
  ('ministry-be-just', 'ministry', 'Senatsverwaltung für Justiz und Verbraucherschutz', null, 'land', 'geo-land-berlin', array['SenJustV']),
  ('ministry-be-kult', 'ministry', 'Senatsverwaltung für Kultur und Gesellschaftlichen Zusammenhalt', null, 'land', 'geo-land-berlin', array['SenKultGZ']),
  ('ministry-be-mvku', 'ministry', 'Senatsverwaltung für Mobilität, Verkehr, Klimaschutz und Umwelt', null, 'land', 'geo-land-berlin', array['SenMVKU']),
  ('ministry-be-stadt', 'ministry', 'Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen', null, 'land', 'geo-land-berlin', array['SenStadt']),
  ('ministry-be-web', 'ministry', 'Senatsverwaltung für Wirtschaft, Energie und Betriebe', null, 'land', 'geo-land-berlin', array['SenWEB']),
  ('ministry-be-wgp', 'ministry', 'Senatsverwaltung für Wissenschaft, Gesundheit und Pflege', null, 'land', 'geo-land-berlin', array['SenWGP']),
  ('authority-be-rechnungshof', 'authority', 'Rechnungshof von Berlin', null, 'land', 'geo-land-berlin', '{}'),
  ('authority-be-datenschutz', 'authority', 'Berliner Beauftragte für Datenschutz und Informationsfreiheit', null, 'land', 'geo-land-berlin', array['BlnBDI']),
  ('authority-be-landeswahlleitung', 'authority', 'Landeswahlleiterin für Berlin', null, 'land', 'geo-land-berlin', array['Landeswahlleitung Berlin']),
  ('committee-ltbb-haupt', 'committee', 'Hauptausschuss (Landtag Brandenburg)', null, 'land', 'geo-land-brandenburg', array['Hauptausschuss Brandenburg', 'A1']),
  ('committee-ltbb-petition', 'committee', 'Petitionsausschuss (Landtag Brandenburg)', null, 'land', 'geo-land-brandenburg', array['Petitionsausschuss Brandenburg', 'A2']),
  ('committee-ltbb-wahlpruefung', 'committee', 'Wahlprüfungsausschuss (Landtag Brandenburg)', null, 'land', 'geo-land-brandenburg', '{}'),
  ('committee-ltbb-inneres', 'committee', 'Ausschuss für Inneres und Kommunales', null, 'land', 'geo-land-brandenburg', array['A3']),
  ('committee-ltbb-recht', 'committee', 'Ausschuss für Recht und Digitalisierung', null, 'land', 'geo-land-brandenburg', array['A4']),
  ('committee-ltbb-bildung', 'committee', 'Ausschuss für Bildung, Jugend und Sport', null, 'land', 'geo-land-brandenburg', array['A5']),
  ('committee-ltbb-wissenschaft', 'committee', 'Ausschuss für Wissenschaft, Forschung und Kultur', null, 'land', 'geo-land-brandenburg', array['A6']),
  ('committee-ltbb-soziales', 'committee', 'Ausschuss für Arbeit, Soziales, Gesundheit und gesellschaftlichen Zusammenhalt', null, 'land', 'geo-land-brandenburg', array['A7']),
  ('committee-ltbb-wirtschaft', 'committee', 'Ausschuss für Wirtschaft, Energie und Klimaschutz', null, 'land', 'geo-land-brandenburg', array['A8']),
  ('committee-ltbb-landwirtschaft', 'committee', 'Ausschuss für Land- und Ernährungswirtschaft, Umwelt und Verbraucherschutz', null, 'land', 'geo-land-brandenburg', array['A9']),
  ('committee-ltbb-infrastruktur', 'committee', 'Ausschuss für Infrastruktur und Landesplanung', null, 'land', 'geo-land-brandenburg', array['A10']),
  ('committee-ltbb-haushalt', 'committee', 'Ausschuss für Haushalt und Finanzen', null, 'land', 'geo-land-brandenburg', array['A11']),
  ('committee-ltbb-haushaltskontrolle', 'committee', 'Ausschuss für Haushaltskontrolle', null, 'land', 'geo-land-brandenburg', array['A12']),
  ('committee-ltbb-europa', 'committee', 'Ausschuss für Europaangelegenheiten und Entwicklungspolitik', null, 'land', 'geo-land-brandenburg', array['A13']),
  ('group-ltbb-spd', 'parliamentary_group', 'SPD-Fraktion im Landtag Brandenburg', null, 'land', 'geo-land-brandenburg', array['SPD-Fraktion Brandenburg']),
  ('group-ltbb-afd', 'parliamentary_group', 'AfD-Fraktion im Landtag Brandenburg', null, 'land', 'geo-land-brandenburg', array['AfD-Fraktion Brandenburg']),
  ('group-ltbb-cdu', 'parliamentary_group', 'CDU-Fraktion im Landtag Brandenburg', null, 'land', 'geo-land-brandenburg', array['CDU-Fraktion Brandenburg']),
  ('group-ltbb-bsw', 'parliamentary_group', 'BSW-Fraktion im Landtag Brandenburg', null, 'land', 'geo-land-brandenburg', array['BSW-Fraktion Brandenburg']),
  ('group-ltbb-wfb', 'parliamentary_group', 'Gruppe Wir für Brandenburg im Landtag Brandenburg', null, 'land', 'geo-land-brandenburg', array['Wir für Brandenburg', 'WfB']),
  ('ministry-bb-stk', 'ministry', 'Staatskanzlei des Landes Brandenburg', null, 'land', 'geo-land-brandenburg', array['Staatskanzlei Brandenburg', 'StK Brandenburg']),
  ('ministry-bb-mik', 'ministry', 'Ministerium des Innern und für Kommunales', null, 'land', 'geo-land-brandenburg', array['MIK Brandenburg']),
  ('ministry-bb-mdf', 'ministry', 'Ministerium der Finanzen', null, 'land', 'geo-land-brandenburg', array['MdF Brandenburg']),
  ('ministry-bb-mdjd', 'ministry', 'Ministerium der Justiz und für Digitalisierung', null, 'land', 'geo-land-brandenburg', array['MdJD Brandenburg']),
  ('ministry-bb-mweke', 'ministry', 'Ministerium für Wirtschaft, Energie, Klimaschutz und Europa', null, 'land', 'geo-land-brandenburg', array['MWEKE Brandenburg']),
  ('ministry-bb-masgz', 'ministry', 'Ministerium für Arbeit, Soziales, Gesundheit und gesellschaftlichen Zusammenhalt', null, 'land', 'geo-land-brandenburg', array['MASGZ Brandenburg']),
  ('ministry-bb-mbjs', 'ministry', 'Ministerium für Bildung, Jugend und Sport', null, 'land', 'geo-land-brandenburg', array['MBJS Brandenburg']),
  ('ministry-bb-mwfk', 'ministry', 'Ministerium für Wissenschaft, Forschung und Kultur', null, 'land', 'geo-land-brandenburg', array['MWFK Brandenburg']),
  ('ministry-bb-mleuv', 'ministry', 'Ministerium für Land- und Ernährungswirtschaft, Umwelt und Verbraucherschutz', null, 'land', 'geo-land-brandenburg', array['MLEUV Brandenburg']),
  ('ministry-bb-mil', 'ministry', 'Ministerium für Infrastruktur und Landesplanung', null, 'land', 'geo-land-brandenburg', array['MIL Brandenburg']),
  ('authority-bb-lrh', 'authority', 'Landesrechnungshof Brandenburg', null, 'land', 'geo-land-brandenburg', array['LRH Brandenburg']),
  ('authority-bb-verfg', 'authority', 'Verfassungsgericht des Landes Brandenburg', null, 'land', 'geo-land-brandenburg', '{}'),
  ('authority-bb-lda', 'authority', 'Landesbeauftragte für den Datenschutz und für das Recht auf Akteneinsicht Brandenburg', null, 'land', 'geo-land-brandenburg', array['LDA Brandenburg']),
  ('authority-bb-landeswahlleitung', 'authority', 'Landeswahlleiterin des Landes Brandenburg', null, 'land', 'geo-land-brandenburg', array['Landeswahlleitung Brandenburg'])
on conflict (id) do nothing;


-- 2) Wahlkreise (122: 78 AGH Berlin [Einteilung 2026] + 44 Landtag Brandenburg [LTW 2024])
insert into public.electoral_districts (id, kind, number, name, geography_id) values
  ('wk-agh-mitte-1', 'landtagswahlkreis', 1, 'Mitte 1', 'geo-land-berlin'),
  ('wk-agh-mitte-2', 'landtagswahlkreis', 2, 'Mitte 2', 'geo-land-berlin'),
  ('wk-agh-mitte-3', 'landtagswahlkreis', 3, 'Mitte 3', 'geo-land-berlin'),
  ('wk-agh-mitte-4', 'landtagswahlkreis', 4, 'Mitte 4', 'geo-land-berlin'),
  ('wk-agh-mitte-5', 'landtagswahlkreis', 5, 'Mitte 5', 'geo-land-berlin'),
  ('wk-agh-mitte-6', 'landtagswahlkreis', 6, 'Mitte 6', 'geo-land-berlin'),
  ('wk-agh-mitte-7', 'landtagswahlkreis', 7, 'Mitte 7', 'geo-land-berlin'),
  ('wk-agh-friedrichshain-kreuzberg-1', 'landtagswahlkreis', 1, 'Friedrichshain-Kreuzberg 1', 'geo-land-berlin'),
  ('wk-agh-friedrichshain-kreuzberg-2', 'landtagswahlkreis', 2, 'Friedrichshain-Kreuzberg 2', 'geo-land-berlin'),
  ('wk-agh-friedrichshain-kreuzberg-3', 'landtagswahlkreis', 3, 'Friedrichshain-Kreuzberg 3', 'geo-land-berlin'),
  ('wk-agh-friedrichshain-kreuzberg-4', 'landtagswahlkreis', 4, 'Friedrichshain-Kreuzberg 4', 'geo-land-berlin'),
  ('wk-agh-friedrichshain-kreuzberg-5', 'landtagswahlkreis', 5, 'Friedrichshain-Kreuzberg 5', 'geo-land-berlin'),
  ('wk-agh-pankow-1', 'landtagswahlkreis', 1, 'Pankow 1', 'geo-land-berlin'),
  ('wk-agh-pankow-2', 'landtagswahlkreis', 2, 'Pankow 2', 'geo-land-berlin'),
  ('wk-agh-pankow-3', 'landtagswahlkreis', 3, 'Pankow 3', 'geo-land-berlin'),
  ('wk-agh-pankow-4', 'landtagswahlkreis', 4, 'Pankow 4', 'geo-land-berlin'),
  ('wk-agh-pankow-5', 'landtagswahlkreis', 5, 'Pankow 5', 'geo-land-berlin'),
  ('wk-agh-pankow-6', 'landtagswahlkreis', 6, 'Pankow 6', 'geo-land-berlin'),
  ('wk-agh-pankow-7', 'landtagswahlkreis', 7, 'Pankow 7', 'geo-land-berlin'),
  ('wk-agh-pankow-8', 'landtagswahlkreis', 8, 'Pankow 8', 'geo-land-berlin'),
  ('wk-agh-pankow-9', 'landtagswahlkreis', 9, 'Pankow 9', 'geo-land-berlin'),
  ('wk-agh-charlottenburg-wilmersdorf-1', 'landtagswahlkreis', 1, 'Charlottenburg-Wilmersdorf 1', 'geo-land-berlin'),
  ('wk-agh-charlottenburg-wilmersdorf-2', 'landtagswahlkreis', 2, 'Charlottenburg-Wilmersdorf 2', 'geo-land-berlin'),
  ('wk-agh-charlottenburg-wilmersdorf-3', 'landtagswahlkreis', 3, 'Charlottenburg-Wilmersdorf 3', 'geo-land-berlin'),
  ('wk-agh-charlottenburg-wilmersdorf-4', 'landtagswahlkreis', 4, 'Charlottenburg-Wilmersdorf 4', 'geo-land-berlin'),
  ('wk-agh-charlottenburg-wilmersdorf-5', 'landtagswahlkreis', 5, 'Charlottenburg-Wilmersdorf 5', 'geo-land-berlin'),
  ('wk-agh-charlottenburg-wilmersdorf-6', 'landtagswahlkreis', 6, 'Charlottenburg-Wilmersdorf 6', 'geo-land-berlin'),
  ('wk-agh-charlottenburg-wilmersdorf-7', 'landtagswahlkreis', 7, 'Charlottenburg-Wilmersdorf 7', 'geo-land-berlin'),
  ('wk-agh-spandau-1', 'landtagswahlkreis', 1, 'Spandau 1', 'geo-land-berlin'),
  ('wk-agh-spandau-2', 'landtagswahlkreis', 2, 'Spandau 2', 'geo-land-berlin'),
  ('wk-agh-spandau-3', 'landtagswahlkreis', 3, 'Spandau 3', 'geo-land-berlin'),
  ('wk-agh-spandau-4', 'landtagswahlkreis', 4, 'Spandau 4', 'geo-land-berlin'),
  ('wk-agh-spandau-5', 'landtagswahlkreis', 5, 'Spandau 5', 'geo-land-berlin'),
  ('wk-agh-steglitz-zehlendorf-1', 'landtagswahlkreis', 1, 'Steglitz-Zehlendorf 1', 'geo-land-berlin'),
  ('wk-agh-steglitz-zehlendorf-2', 'landtagswahlkreis', 2, 'Steglitz-Zehlendorf 2', 'geo-land-berlin'),
  ('wk-agh-steglitz-zehlendorf-3', 'landtagswahlkreis', 3, 'Steglitz-Zehlendorf 3', 'geo-land-berlin'),
  ('wk-agh-steglitz-zehlendorf-4', 'landtagswahlkreis', 4, 'Steglitz-Zehlendorf 4', 'geo-land-berlin'),
  ('wk-agh-steglitz-zehlendorf-5', 'landtagswahlkreis', 5, 'Steglitz-Zehlendorf 5', 'geo-land-berlin'),
  ('wk-agh-steglitz-zehlendorf-6', 'landtagswahlkreis', 6, 'Steglitz-Zehlendorf 6', 'geo-land-berlin'),
  ('wk-agh-steglitz-zehlendorf-7', 'landtagswahlkreis', 7, 'Steglitz-Zehlendorf 7', 'geo-land-berlin'),
  ('wk-agh-tempelhof-schoeneberg-1', 'landtagswahlkreis', 1, 'Tempelhof-Schöneberg 1', 'geo-land-berlin'),
  ('wk-agh-tempelhof-schoeneberg-2', 'landtagswahlkreis', 2, 'Tempelhof-Schöneberg 2', 'geo-land-berlin'),
  ('wk-agh-tempelhof-schoeneberg-3', 'landtagswahlkreis', 3, 'Tempelhof-Schöneberg 3', 'geo-land-berlin'),
  ('wk-agh-tempelhof-schoeneberg-4', 'landtagswahlkreis', 4, 'Tempelhof-Schöneberg 4', 'geo-land-berlin'),
  ('wk-agh-tempelhof-schoeneberg-5', 'landtagswahlkreis', 5, 'Tempelhof-Schöneberg 5', 'geo-land-berlin'),
  ('wk-agh-tempelhof-schoeneberg-6', 'landtagswahlkreis', 6, 'Tempelhof-Schöneberg 6', 'geo-land-berlin'),
  ('wk-agh-tempelhof-schoeneberg-7', 'landtagswahlkreis', 7, 'Tempelhof-Schöneberg 7', 'geo-land-berlin'),
  ('wk-agh-neukoelln-1', 'landtagswahlkreis', 1, 'Neukölln 1', 'geo-land-berlin'),
  ('wk-agh-neukoelln-2', 'landtagswahlkreis', 2, 'Neukölln 2', 'geo-land-berlin'),
  ('wk-agh-neukoelln-3', 'landtagswahlkreis', 3, 'Neukölln 3', 'geo-land-berlin'),
  ('wk-agh-neukoelln-4', 'landtagswahlkreis', 4, 'Neukölln 4', 'geo-land-berlin'),
  ('wk-agh-neukoelln-5', 'landtagswahlkreis', 5, 'Neukölln 5', 'geo-land-berlin'),
  ('wk-agh-neukoelln-6', 'landtagswahlkreis', 6, 'Neukölln 6', 'geo-land-berlin'),
  ('wk-agh-treptow-koepenick-1', 'landtagswahlkreis', 1, 'Treptow-Köpenick 1', 'geo-land-berlin'),
  ('wk-agh-treptow-koepenick-2', 'landtagswahlkreis', 2, 'Treptow-Köpenick 2', 'geo-land-berlin'),
  ('wk-agh-treptow-koepenick-3', 'landtagswahlkreis', 3, 'Treptow-Köpenick 3', 'geo-land-berlin'),
  ('wk-agh-treptow-koepenick-4', 'landtagswahlkreis', 4, 'Treptow-Köpenick 4', 'geo-land-berlin'),
  ('wk-agh-treptow-koepenick-5', 'landtagswahlkreis', 5, 'Treptow-Köpenick 5', 'geo-land-berlin'),
  ('wk-agh-treptow-koepenick-6', 'landtagswahlkreis', 6, 'Treptow-Köpenick 6', 'geo-land-berlin'),
  ('wk-agh-treptow-koepenick-7', 'landtagswahlkreis', 7, 'Treptow-Köpenick 7', 'geo-land-berlin'),
  ('wk-agh-marzahn-hellersdorf-1', 'landtagswahlkreis', 1, 'Marzahn-Hellersdorf 1', 'geo-land-berlin'),
  ('wk-agh-marzahn-hellersdorf-2', 'landtagswahlkreis', 2, 'Marzahn-Hellersdorf 2', 'geo-land-berlin'),
  ('wk-agh-marzahn-hellersdorf-3', 'landtagswahlkreis', 3, 'Marzahn-Hellersdorf 3', 'geo-land-berlin'),
  ('wk-agh-marzahn-hellersdorf-4', 'landtagswahlkreis', 4, 'Marzahn-Hellersdorf 4', 'geo-land-berlin'),
  ('wk-agh-marzahn-hellersdorf-5', 'landtagswahlkreis', 5, 'Marzahn-Hellersdorf 5', 'geo-land-berlin'),
  ('wk-agh-marzahn-hellersdorf-6', 'landtagswahlkreis', 6, 'Marzahn-Hellersdorf 6', 'geo-land-berlin'),
  ('wk-agh-lichtenberg-1', 'landtagswahlkreis', 1, 'Lichtenberg 1', 'geo-land-berlin'),
  ('wk-agh-lichtenberg-2', 'landtagswahlkreis', 2, 'Lichtenberg 2', 'geo-land-berlin'),
  ('wk-agh-lichtenberg-3', 'landtagswahlkreis', 3, 'Lichtenberg 3', 'geo-land-berlin'),
  ('wk-agh-lichtenberg-4', 'landtagswahlkreis', 4, 'Lichtenberg 4', 'geo-land-berlin'),
  ('wk-agh-lichtenberg-5', 'landtagswahlkreis', 5, 'Lichtenberg 5', 'geo-land-berlin'),
  ('wk-agh-lichtenberg-6', 'landtagswahlkreis', 6, 'Lichtenberg 6', 'geo-land-berlin'),
  ('wk-agh-reinickendorf-1', 'landtagswahlkreis', 1, 'Reinickendorf 1', 'geo-land-berlin'),
  ('wk-agh-reinickendorf-2', 'landtagswahlkreis', 2, 'Reinickendorf 2', 'geo-land-berlin'),
  ('wk-agh-reinickendorf-3', 'landtagswahlkreis', 3, 'Reinickendorf 3', 'geo-land-berlin'),
  ('wk-agh-reinickendorf-4', 'landtagswahlkreis', 4, 'Reinickendorf 4', 'geo-land-berlin'),
  ('wk-agh-reinickendorf-5', 'landtagswahlkreis', 5, 'Reinickendorf 5', 'geo-land-berlin'),
  ('wk-agh-reinickendorf-6', 'landtagswahlkreis', 6, 'Reinickendorf 6', 'geo-land-berlin'),
  ('wk-ltbb-1', 'landtagswahlkreis', 1, 'Prignitz I', 'geo-land-brandenburg'),
  ('wk-ltbb-2', 'landtagswahlkreis', 2, 'Prignitz II / Ostprignitz-Ruppin II', 'geo-land-brandenburg'),
  ('wk-ltbb-3', 'landtagswahlkreis', 3, 'Ostprignitz-Ruppin I', 'geo-land-brandenburg'),
  ('wk-ltbb-4', 'landtagswahlkreis', 4, 'Ostprignitz-Ruppin III / Havelland III', 'geo-land-brandenburg'),
  ('wk-ltbb-5', 'landtagswahlkreis', 5, 'Havelland I', 'geo-land-brandenburg'),
  ('wk-ltbb-6', 'landtagswahlkreis', 6, 'Havelland II', 'geo-land-brandenburg'),
  ('wk-ltbb-7', 'landtagswahlkreis', 7, 'Oberhavel I', 'geo-land-brandenburg'),
  ('wk-ltbb-8', 'landtagswahlkreis', 8, 'Oberhavel II', 'geo-land-brandenburg'),
  ('wk-ltbb-9', 'landtagswahlkreis', 9, 'Oberhavel III', 'geo-land-brandenburg'),
  ('wk-ltbb-10', 'landtagswahlkreis', 10, 'Uckermark III / Oberhavel IV', 'geo-land-brandenburg'),
  ('wk-ltbb-11', 'landtagswahlkreis', 11, 'Uckermark I', 'geo-land-brandenburg'),
  ('wk-ltbb-12', 'landtagswahlkreis', 12, 'Uckermark II', 'geo-land-brandenburg'),
  ('wk-ltbb-13', 'landtagswahlkreis', 13, 'Barnim I', 'geo-land-brandenburg'),
  ('wk-ltbb-14', 'landtagswahlkreis', 14, 'Barnim II', 'geo-land-brandenburg'),
  ('wk-ltbb-15', 'landtagswahlkreis', 15, 'Barnim III', 'geo-land-brandenburg'),
  ('wk-ltbb-16', 'landtagswahlkreis', 16, 'Brandenburg an der Havel I / Potsdam-Mittelmark I', 'geo-land-brandenburg'),
  ('wk-ltbb-17', 'landtagswahlkreis', 17, 'Brandenburg an der Havel II', 'geo-land-brandenburg'),
  ('wk-ltbb-18', 'landtagswahlkreis', 18, 'Potsdam-Mittelmark II', 'geo-land-brandenburg'),
  ('wk-ltbb-19', 'landtagswahlkreis', 19, 'Potsdam-Mittelmark III / Potsdam III', 'geo-land-brandenburg'),
  ('wk-ltbb-20', 'landtagswahlkreis', 20, 'Potsdam-Mittelmark IV', 'geo-land-brandenburg'),
  ('wk-ltbb-21', 'landtagswahlkreis', 21, 'Potsdam I', 'geo-land-brandenburg'),
  ('wk-ltbb-22', 'landtagswahlkreis', 22, 'Potsdam II', 'geo-land-brandenburg'),
  ('wk-ltbb-23', 'landtagswahlkreis', 23, 'Teltow-Fläming I', 'geo-land-brandenburg'),
  ('wk-ltbb-24', 'landtagswahlkreis', 24, 'Teltow-Fläming II', 'geo-land-brandenburg'),
  ('wk-ltbb-25', 'landtagswahlkreis', 25, 'Teltow-Fläming III', 'geo-land-brandenburg'),
  ('wk-ltbb-26', 'landtagswahlkreis', 26, 'Dahme-Spreewald I', 'geo-land-brandenburg'),
  ('wk-ltbb-27', 'landtagswahlkreis', 27, 'Dahme-Spreewald II / Oder-Spree I', 'geo-land-brandenburg'),
  ('wk-ltbb-28', 'landtagswahlkreis', 28, 'Dahme-Spreewald III', 'geo-land-brandenburg'),
  ('wk-ltbb-29', 'landtagswahlkreis', 29, 'Oder-Spree II', 'geo-land-brandenburg'),
  ('wk-ltbb-30', 'landtagswahlkreis', 30, 'Oder-Spree III', 'geo-land-brandenburg'),
  ('wk-ltbb-31', 'landtagswahlkreis', 31, 'Märkisch-Oderland I / Oder-Spree IV', 'geo-land-brandenburg'),
  ('wk-ltbb-32', 'landtagswahlkreis', 32, 'Märkisch-Oderland II', 'geo-land-brandenburg'),
  ('wk-ltbb-33', 'landtagswahlkreis', 33, 'Märkisch-Oderland III', 'geo-land-brandenburg'),
  ('wk-ltbb-34', 'landtagswahlkreis', 34, 'Märkisch-Oderland IV', 'geo-land-brandenburg'),
  ('wk-ltbb-35', 'landtagswahlkreis', 35, 'Frankfurt (Oder)', 'geo-land-brandenburg'),
  ('wk-ltbb-36', 'landtagswahlkreis', 36, 'Elbe-Elster I', 'geo-land-brandenburg'),
  ('wk-ltbb-37', 'landtagswahlkreis', 37, 'Elbe-Elster II', 'geo-land-brandenburg'),
  ('wk-ltbb-38', 'landtagswahlkreis', 38, 'Oberspreewald-Lausitz I', 'geo-land-brandenburg'),
  ('wk-ltbb-39', 'landtagswahlkreis', 39, 'Oberspreewald-Lausitz II / Spree-Neiße IV', 'geo-land-brandenburg'),
  ('wk-ltbb-40', 'landtagswahlkreis', 40, 'Oberspreewald-Lausitz III / Spree-Neiße III', 'geo-land-brandenburg'),
  ('wk-ltbb-41', 'landtagswahlkreis', 41, 'Spree-Neiße I', 'geo-land-brandenburg'),
  ('wk-ltbb-42', 'landtagswahlkreis', 42, 'Spree-Neiße II', 'geo-land-brandenburg'),
  ('wk-ltbb-43', 'landtagswahlkreis', 43, 'Cottbus I', 'geo-land-brandenburg'),
  ('wk-ltbb-44', 'landtagswahlkreis', 44, 'Cottbus II', 'geo-land-brandenburg')
on conflict (id) do nothing;


-- Integritaets-Selbstpruefung (erwartet 0 Zeilen): keine Entitaet ausserhalb Ebene 'land'.
-- select id from public.political_entities where id like any(array['committee-agh-%','committee-ltbb-%','ministry-be-%','ministry-bb-%','group-agh-%','group-ltbb-%','authority-be-%','authority-bb-%']) and level <> 'land';

commit;
notify pgrst, 'reload schema';
