import type { PoliticianProfile, RawItem, Source } from "./types";

export const cemInceProfile: PoliticianProfile = {
  id: "cem-ince",
  fullName: "Cem Ince",
  party: "Die Linke",
  faction: "Die Linke",
  function: "Bundestagsabgeordneter",
  constituency: "Noch offen",
  state: "Noch offen",
  location: "Noch offen",
  committee: "Arbeit und Soziales",
  committees: ["Arbeit und Soziales"],
  committeeUnknown: false,
  focusTopics: [
    "Arbeit",
    "Soziales",
    "Bürgergeld",
    "Rente",
    "Mindestlohn",
    "Tarifbindung",
    "Arbeitsmarkt",
    "Pflege",
    "Sozialstaat",
    "Armut",
    "Gewerkschaften",
    "Bundesregierung Vorhaben im Bereich Arbeit und Soziales"
  ],
  topicPriorities: {
    Arbeit: 5,
    Soziales: 5,
    Bürgergeld: 5,
    Mindestlohn: 5,
    Pflege: 4,
    Wohnen: 2,
    Migration: 2,
    Bildung: 2,
    Klima: 1,
    Energie: 2,
    Digitalisierung: 2,
    Außenpolitik: 1,
    Verteidigung: 1,
    Europa: 2,
    Familie: 3,
    Rente: 5,
    Gesundheit: 3,
    Tarifbindung: 5,
    Arbeitsmarkt: 5,
    Gewerkschaften: 5
  },
  mainQuestion:
    "Welche Pläne hat die Bundesregierung im Bereich Arbeit und Soziales und worauf sollte ich politisch reagieren?",
  monitoringTargets: [
    "Meine Partei",
    "Meine Person",
    "Mein Fachausschuss",
    "Bundesregierung Vorhaben",
    "Arbeit und Soziales"
  ],
  outputNeeds: [
    "Was ist heute wichtig?",
    "Was kann ignoriert werden?",
    "Worauf sollte ich reagieren?",
    "Welche Chance entsteht?",
    "Welches Risiko entsteht?",
    "Welche Formulierung kann ich nutzen?"
  ],
  regionalInterests: ["lokale Beschäftigung", "Pflegeversorgung", "Armutsbekämpfung", "Tarifbindung vor Ort"],
  relevantMinistries: ["BMAS", "BMG", "BMF", "Bundesregierung"],
  opponents: ["CDU/CSU", "SPD-Regierungslinie", "FDP", "AfD"],
  localMedia: ["taz", "nd", "regionale Tageszeitung", "Lokalradio"],
  communicationStyle: "Lösungsorientiert",
  noGoTopics: ["unbelegte persönliche Angriffe", "verkürzte Kulturkampf-Frames", "unklare Forderungen ohne Handlungsvorschlag"]
};

export const demoSources: Source[] = [
  { id: "source-party", name: "Die Linke Tageslage", type: "party", url: "https://die-linke.de", priority: 90, active: true },
  { id: "source-person", name: "Cem Ince Monitoring", type: "person", url: "https://example.local/cem-ince", priority: 100, active: true },
  { id: "source-committee", name: "Ausschuss Arbeit und Soziales", type: "committee", url: "https://bundestag.de", priority: 92, active: true },
  { id: "source-bundestag", name: "Bundestag Heute", type: "bundestag", url: "https://bundestag.de/heute", priority: 82, active: true },
  { id: "source-ministry", name: "BMAS Vorhabenradar", type: "ministry", url: "https://bmas.de", priority: 95, active: true },
  { id: "source-local", name: "Regionale Tageszeitung", type: "local", url: "https://example.local/regional", priority: 74, active: true },
  { id: "source-association", name: "Gewerkschafts- und Sozialverbandslage", type: "association", url: "https://example.local/verband", priority: 84, active: true },
  { id: "source-social", name: "Social Scan", type: "social", url: "https://example.local/social", priority: 60, active: true },
  { id: "source-media", name: "Politik Morgen", type: "media", url: "https://example.local/politik", priority: 55, active: true }
];

export const demoRawItems: RawItem[] = [
  {
    id: "raw-bmas-tariftreue",
    sourceId: "source-ministry",
    sourceName: "BMAS Pressemitteilung",
    sourceType: "ministry",
    sourceUrl: "https://bmas.de",
    title: "BMAS legt Eckpunkte für Bundestariftreuegesetz vor",
    url: "https://example.local/bmas-tariftreue",
    content:
      "Das Bundesarbeitsministerium kündigt Eckpunkte für ein Bundestariftreuegesetz an. Öffentliche Aufträge des Bundes sollen stärker an Tarifbindung geknüpft werden; Details zur Kontrolle bleiben offen.",
    publishedAt: "2026-06-17T06:05:00+02:00",
    retrievedAt: "2026-06-17T06:12:00+02:00",
    author: "BMAS Vorhabenradar",
    excerpt: "Öffentliche Aufträge des Bundes sollen stärker an Tarifbindung geknüpft werden.",
    confidence: "high",
    hash: "mock-001",
    category: "Bundesregierung Vorhaben im Bereich Arbeit und Soziales"
  },
  {
    id: "raw-linke-buergergeld",
    sourceId: "source-party",
    sourceName: "Die Linke Fraktion",
    sourceType: "party",
    sourceUrl: "https://die-linke.de",
    title: "Die Linke fordert Gegenlinie zu geplanten Bürgergeld-Sanktionen",
    url: "https://example.local/linke-buergergeld",
    content:
      "Die Linke will die Bundesregierung wegen neuer Bürgergeld-Sanktionspläne angreifen. Die Fraktion sucht Stimmen aus dem Ausschuss Arbeit und Soziales für eine klare soziale Gegenposition.",
    publishedAt: "2026-06-17T06:18:00+02:00",
    retrievedAt: "2026-06-17T06:22:00+02:00",
    author: "Parteiredaktion",
    excerpt: "Die Fraktion sucht Stimmen aus dem Ausschuss Arbeit und Soziales für eine klare soziale Gegenposition.",
    confidence: "high",
    hash: "mock-002",
    category: "Berichterstattung über Die Linke"
  },
  {
    id: "raw-cem-ince-mindestlohn",
    sourceId: "source-person",
    sourceName: "Tagesschau Anfrage und Social Media Signale",
    sourceType: "media",
    sourceUrl: "https://example.local/cem-ince",
    title: "Deine Mindestlohnforderung wird in der Morgenlage aufgegriffen",
    url: "https://example.local/cem-ince-mindestlohn",
    content:
      "Mehrere Accounts greifen deine Forderung nach einem höheren Mindestlohn auf. Eine Redaktion fragt nach, ob du die Bundesregierung noch vor der Ausschusssitzung öffentlich adressieren willst.",
    publishedAt: "2026-06-17T06:32:00+02:00",
    retrievedAt: "2026-06-17T06:36:00+02:00",
    author: "Cem Ince Monitoring",
    excerpt: "Eine Redaktion fragt nach, ob du die Bundesregierung noch vor der Ausschusssitzung öffentlich adressieren willst.",
    confidence: "medium",
    hash: "mock-003",
    category: "Berichterstattung über Cem Ince"
  },
  {
    id: "raw-committee-pflege",
    sourceId: "source-committee",
    sourceName: "Bundestag Ausschusskalender",
    sourceType: "committee",
    sourceUrl: "https://bundestag.de",
    title: "Ausschuss Arbeit und Soziales setzt Pflege-Arbeitsbedingungen auf Tagesordnung",
    url: "https://example.local/ausschuss-pflege",
    content:
      "Der Ausschuss Arbeit und Soziales behandelt heute Arbeitsbedingungen in der Pflege. Erwartet werden Fragen zu Dienstplänen, Personalmangel, Tarifbindung und Finanzierung.",
    publishedAt: "2026-06-17T06:45:00+02:00",
    retrievedAt: "2026-06-17T06:50:00+02:00",
    author: "Parlamentsdienst",
    excerpt: "Der Ausschuss Arbeit und Soziales behandelt heute Arbeitsbedingungen in der Pflege.",
    confidence: "high",
    hash: "mock-004",
    category: "Berichterstattung über seinen Fachausschuss"
  },
  {
    id: "raw-bundestag-rente",
    sourceId: "source-bundestag",
    sourceName: "Bundestag Tagesordnung",
    sourceType: "bundestag",
    sourceUrl: "https://bundestag.de",
    title: "Bundestag debattiert Rentenpaket der Bundesregierung",
    url: "https://example.local/rentenpaket",
    content:
      "Auf der Tagesordnung steht ein Rentenpaket der Bundesregierung. Kritisiert werden unklare Entlastungen für Menschen mit niedrigen Einkommen und offene Finanzierungsfragen.",
    publishedAt: "2026-06-17T07:00:00+02:00",
    retrievedAt: "2026-06-17T07:05:00+02:00",
    author: "Bundestagsdienst",
    excerpt: "Auf der Tagesordnung steht ein Rentenpaket der Bundesregierung.",
    confidence: "high",
    hash: "mock-005",
    category: "Bundestag Thema"
  },
  {
    id: "raw-ministry-arbeitsmarkt",
    sourceId: "source-ministry",
    sourceName: "Bundesregierung",
    sourceType: "ministry",
    sourceUrl: "https://bundesregierung.de",
    title: "Bundesregierung kündigt Initiative zur Arbeitsmarktintegration an",
    url: "https://example.local/arbeitsmarktinitiative",
    content:
      "Die Bundesregierung plant eine Initiative zur Arbeitsmarktintegration. Vorgesehen sind schnellere Vermittlung, Qualifizierung und strengere Mitwirkungspflichten.",
    publishedAt: "2026-06-17T07:16:00+02:00",
    retrievedAt: "2026-06-17T07:19:00+02:00",
    author: "Ministeriumsradar",
    excerpt: "Vorgesehen sind schnellere Vermittlung, Qualifizierung und strengere Mitwirkungspflichten.",
    confidence: "high",
    hash: "mock-006",
    category: "Ministerium Thema"
  },
  {
    id: "raw-local-pflegeheim",
    sourceId: "source-local",
    sourceName: "Lokale Zeitung",
    sourceType: "local",
    sourceUrl: "https://example.local/regional",
    title: "Lokales Pflegeheim warnt vor Dienstplan-Kollaps",
    url: "https://example.local/pflegeheim-dienstplan",
    content:
      "Ein Pflegeheim in der Region warnt vor kurzfristigen Dienstplan-Ausfällen. Beschäftigte fordern bessere Arbeitsbedingungen und verlässliche Personalstandards.",
    publishedAt: "2026-06-17T07:25:00+02:00",
    retrievedAt: "2026-06-17T07:30:00+02:00",
    author: "Regionaldesk",
    excerpt: "Beschäftigte fordern bessere Arbeitsbedingungen und verlässliche Personalstandards.",
    confidence: "medium",
    hash: "mock-007",
    category: "Lokales Thema"
  },
  {
    id: "raw-union-tarifbindung",
    sourceId: "source-association",
    sourceName: "DGB Reaktion",
    sourceType: "association",
    sourceUrl: "https://dgb.de",
    title: "Gewerkschaften begrüßen Tariftreuepläne, warnen aber vor Schlupflöchern",
    url: "https://example.local/gewerkschaften-tariftreue",
    content:
      "Gewerkschaften unterstützen das Vorhaben der Bundesregierung zur Tariftreue, fordern aber wirksame Kontrollen und Sanktionen. Jetzt suchen sie parlamentarische Verbündete.",
    publishedAt: "2026-06-17T07:33:00+02:00",
    retrievedAt: "2026-06-17T07:37:00+02:00",
    author: "Gewerkschaftslage",
    excerpt: "Gewerkschaften fordern wirksame Kontrollen und Sanktionen.",
    confidence: "high",
    hash: "mock-008",
    category: "Verbandsreaktion"
  },
  {
    id: "raw-risk-sanktionsframe",
    sourceId: "source-social",
    sourceName: "Reichweitenstarker Social Media Account",
    sourceType: "social",
    sourceUrl: "https://example.local/social",
    title: "Reichweitenstarker Account rahmt deine Bürgergeldposition als Schutz von Leistungsverweigerung",
    url: "https://example.local/social-risk",
    content:
      "Ein reichweitenstarker Account greift deine Bürgergeldposition persönlich an und verbindet sie mit dem Vorwurf, Leistungsverweigerung zu schützen. Erste Kommentare greifen den Frame auf.",
    publishedAt: "2026-06-17T07:41:00+02:00",
    retrievedAt: "2026-06-17T07:44:00+02:00",
    author: "Social Scan",
    excerpt: "Erste Kommentare greifen den Frame auf.",
    confidence: "low",
    hash: "mock-009",
    category: "Kritisches Risiko"
  },
  {
    id: "raw-irrelevant-sport",
    sourceId: "source-media",
    sourceName: "Lokale Zeitung",
    sourceType: "media",
    sourceUrl: "https://example.local/politik",
    title: "Sportverein stellt neues Trikotdesign für die kommende Saison vor",
    url: "https://example.local/trikotdesign",
    content:
      "Der lokale Sportverein präsentiert neue Farben und einen Sponsor. Für deine heutigen fachpolitischen Fragen entsteht daraus kein politischer Handlungsbedarf.",
    publishedAt: "2026-06-17T08:02:00+02:00",
    retrievedAt: "2026-06-17T08:07:00+02:00",
    author: "Sportredaktion",
    excerpt: "Der lokale Sportverein präsentiert neue Farben und einen Sponsor.",
    confidence: "medium",
    hash: "mock-010",
    category: "Irrelevantes Thema"
  }
];
